"use strict";
const ExcelJS = require("exceljs");
const crypto  = require("crypto");

// In-memory store for verified workbooks pending download
const store = new Map();

setInterval(() => {
    const now = Date.now();
    for (const [id, entry] of store) {
        if (entry.expiresAt < now) store.delete(id);
    }
}, 60_000);

// ─── Column indices in the STOCK sheet (1-based) ──────────────────────────────
const COL = {
    BRAND:  1,  // A – Brand Name
    SIZE:   2,  // B – Size
    OB:     3,  // C – O.B. Stock
    CB:     6,  // F – C/B Stock
};

// ─── helpers ──────────────────────────────────────────────────────────────────

function makeKey(brand, size) {
    return `${(brand || "").trim().toUpperCase()}|${(size || "").trim().toUpperCase()}`;
}

function cellNum(cell) {
    if (!cell || cell.value === null || cell.value === undefined || cell.value === "") return 0;
    const v = cell.value;
    if (typeof v === "number") return v;
    if (typeof v === "object" && v.result !== undefined) return typeof v.result === "number" ? v.result : 0;
    const n = parseFloat(String(v));
    return isNaN(n) ? 0 : n;
}

function cellText(cell) {
    if (!cell || cell.value === null || cell.value === undefined) return "";
    const v = cell.value;
    if (typeof v === "object" && v.text  !== undefined) return String(v.text);
    if (typeof v === "object" && v.result !== undefined) return String(v.result);
    return String(v).trim();
}

// ─── Known valid sizes – used to exclude expense / summary rows ──────────────
const VALID_SIZES = new Set(["Q", "P", "N", "D", "DI", "QUARTER", "PINT", "NIP"]);

/**
 * Parse an xlsx buffer into an array of StockRow objects.
 * ONLY rows where BOTH Brand Name AND Size are present are included.
 * This automatically excludes the expense section and cash-summary block,
 * which either have an empty Size cell or no Brand.
 */
async function parseSheet(buffer) {
    const wb = new ExcelJS.Workbook();
    await wb.xlsx.load(buffer);
    const ws = wb.worksheets[0];
    if (!ws) throw new Error("No sheet found in file.");

    // Validate header
    const h1 = cellText(ws.getRow(1).getCell(COL.BRAND));
    const h6 = cellText(ws.getRow(1).getCell(COL.CB));
    if (!h1.toLowerCase().includes("brand") || !h6.toLowerCase().includes("c/b")) {
        throw new Error(
            "Invalid template: expected 'Brand Name' in col A and 'C/B Stock' in col F of row 1. " +
            "Please use only Excel files generated by this app."
        );
    }

    const rows = [];
    ws.eachRow({ includeEmpty: false }, (row, rowIndex) => {
        if (rowIndex === 1) return;
        const brand = cellText(row.getCell(COL.BRAND));
        const size  = cellText(row.getCell(COL.SIZE));
        // Skip rows without BOTH brand AND size – catches expense / summary rows
        if (!brand || !size) return;
        rows.push({
            brand,
            size,
            opening: cellNum(row.getCell(COL.OB)),
            closing: cellNum(row.getCell(COL.CB)),
            rowIndex,
        });
    });
    return rows;
}

/**
 * Main verification logic.
 */
async function verifyDays(yesterdayBuffer, todayBuffer, todayDate) {
    // 1. Parse both sheets
    const yesterdayRows = await parseSheet(yesterdayBuffer);
    const todayRows     = await parseSheet(todayBuffer);

    // 2. Build yesterday lookup: key → closing stock
    const yesterdayMap = new Map();
    for (const row of yesterdayRows) {
        yesterdayMap.set(makeKey(row.brand, row.size), row.closing);
    }

    // 3. Compare
    const results = [];
    for (const row of todayRows) {
        const key         = makeKey(row.brand, row.size);
        const cbYesterday = yesterdayMap.get(key);

        let status, message;
        if (cbYesterday === undefined) {
            status  = "WARNING";
            message = `Not found in yesterday's sheet`;
        } else if (row.opening === cbYesterday) {
            status  = "OK";
            message = `Verified`;
        } else {
            status  = "MISMATCH";
            const diff = row.opening - cbYesterday;
            message = `OB today (${row.opening}) ≠ CB yesterday (${cbYesterday})  [diff: ${diff > 0 ? "+" : ""}${diff}]`;
        }

        results.push({
            brand:        row.brand,
            size:         row.size,
            ob_today:     row.opening,
            cb_yesterday: cbYesterday !== undefined ? cbYesterday : null,
            cb_today:     row.closing,
            status,
            message,
        });
    }

    // 4. Summary
    const summary = {
        total_rows:    results.length,
        ok_rows:       results.filter(r => r.status === "OK").length,
        mismatch_rows: results.filter(r => r.status === "MISMATCH").length,
        warning_rows:  results.filter(r => r.status === "WARNING").length,
    };

    // 5. Build a CLEAN verification report workbook (6 columns only)
    const wb = new ExcelJS.Workbook();
    wb.creator = "JaiDurga Wine Shop AI Accountant";
    wb.created = new Date();

    const ws = wb.addWorksheet(`Verify_${todayDate || "today"}`, {
        pageSetup: { fitToPage: true, fitToWidth: 1 },
        properties: { defaultRowHeight: 18 },
    });

    // ── Column widths ─────────────────────────────────────────────────────────
    ws.getColumn(1).width = 28;  // Brand Name
    ws.getColumn(2).width = 8;   // Size
    ws.getColumn(3).width = 14;  // OB Stock (Today)
    ws.getColumn(4).width = 18;  // Prev Day CB Stock
    ws.getColumn(5).width = 12;  // Status
    ws.getColumn(6).width = 48;  // Notes

    // ── Header row ────────────────────────────────────────────────────────────
    const HDR_FILL  = { type: "pattern", pattern: "solid", fgColor: { argb: "FF1A3C6E" } };
    const HDR_FONT  = { bold: true, color: { argb: "FFFFFFFF" }, size: 11, name: "Calibri" };
    const HDR_ALIGN = { horizontal: "center", vertical: "middle" };

    const headers = ["Brand Name", "Size", "OB Stock (Today)", "Prev Day CB Stock", "Status", "Notes"];
    const hdr = ws.getRow(1);
    hdr.height = 22;
    headers.forEach((h, i) => {
        const cell = hdr.getCell(i + 1);
        cell.value     = h;
        cell.font      = HDR_FONT;
        cell.fill      = HDR_FILL;
        cell.alignment = HDR_ALIGN;
        cell.border    = { bottom: { style: "thin", color: { argb: "FF3A5EA8" } } };
    });
    hdr.commit();

    // Freeze header
    ws.views = [{ state: "frozen", ySplit: 1, showGridLines: true }];

    // ── Data rows ─────────────────────────────────────────────────────────────
    const COLORS = {
        OK:       { row: "FFE8F5E9", status: "FF238636", text: "FF238636" },   // soft green
        MISMATCH: { row: "FFFFEBEE", status: "FFDA3633", text: "FFDA3633" },   // soft red
        WARNING:  { row: "FFFFFDE7", status: "FFB08800", text: "FF7D6000" },   // soft yellow
    };

    results.forEach((r, i) => {
        const row   = ws.getRow(i + 2);
        const clr   = COLORS[r.status] || COLORS.OK;
        const isOdd = i % 2 === 0;

        // Row background
        const rowFill = r.status === "OK"
            ? { type: "pattern", pattern: "solid", fgColor: { argb: isOdd ? "FFFFFFFF" : "FFF5F5F5" } }
            : { type: "pattern", pattern: "solid", fgColor: { argb: clr.row } };

        // -- Col A: Brand Name
        const cBrand = row.getCell(1);
        cBrand.value     = r.brand;
        cBrand.font      = { name: "Calibri", size: 10, bold: r.status !== "OK" };
        cBrand.fill      = rowFill;
        cBrand.alignment = { vertical: "middle" };

        // -- Col B: Size
        const cSize = row.getCell(2);
        cSize.value     = r.size;
        cSize.font      = { name: "Calibri", size: 10 };
        cSize.fill      = rowFill;
        cSize.alignment = { horizontal: "center", vertical: "middle" };

        // -- Col C: OB Stock Today
        const cOB = row.getCell(3);
        cOB.value     = r.ob_today;
        cOB.numFmt    = "#,##0";
        cOB.font      = { name: "Calibri", size: 10 };
        cOB.fill      = rowFill;
        cOB.alignment = { horizontal: "center", vertical: "middle" };

        // -- Col D: Prev Day CB Stock
        const cCB = row.getCell(4);
        cCB.value     = r.cb_yesterday !== null ? r.cb_yesterday : "—";
        cCB.numFmt    = r.cb_yesterday !== null ? "#,##0" : "@";
        cCB.font      = { name: "Calibri", size: 10 };
        cCB.fill      = rowFill;
        cCB.alignment = { horizontal: "center", vertical: "middle" };

        // -- Col E: Status  (short, colour-coded)
        const cStatus = row.getCell(5);
        const statusLabels = { OK: "✓  OK", MISMATCH: "✗  MISMATCH", WARNING: "⚠  WARNING" };
        cStatus.value     = statusLabels[r.status] || r.status;
        cStatus.font      = { bold: true, color: { argb: clr.status }, name: "Calibri", size: 10 };
        cStatus.fill      = rowFill;
        cStatus.alignment = { horizontal: "center", vertical: "middle" };

        // -- Col F: Notes
        const cNote = row.getCell(6);
        cNote.value     = r.message;
        cNote.font      = {
            name:   "Calibri",
            size:   10,
            italic: r.status === "OK",
            color:  { argb: r.status === "OK" ? "FF888888" : clr.text },
        };
        cNote.fill      = rowFill;
        cNote.alignment = { vertical: "middle", wrapText: false };

        row.height = 18;
        row.commit();
    });

    // ── Summary footer row ────────────────────────────────────────────────────
    const footerRowNum = results.length + 3;
    const footer = ws.getRow(footerRowNum);
    footer.getCell(1).value = `Total: ${summary.total_rows}   ✓ OK: ${summary.ok_rows}   ✗ Mismatch: ${summary.mismatch_rows}   ⚠ Warning: ${summary.warning_rows}`;
    footer.getCell(1).font  = { bold: true, color: { argb: "FF1A3C6E" }, size: 10, name: "Calibri" };
    ws.mergeCells(footerRowNum, 1, footerRowNum, 6);
    footer.getCell(1).alignment = { horizontal: "left" };
    footer.commit();

    // 6. Serialize
    const verifiedBuffer = await wb.xlsx.writeBuffer();

    // 7. Store for download
    const id       = crypto.randomBytes(16).toString("hex");
    const filename = `JaiDurga_Verified_${todayDate || "today"}.xlsx`;
    store.set(id, {
        buffer:    verifiedBuffer,
        filename,
        expiresAt: Date.now() + 15 * 60 * 1000,
    });

    return {
        summary,
        previewRows: results,   // ALL rows now (no 50-row cap)
        downloadId:  id,
    };
}

/**
 * Retrieve a stored verified buffer by ID.
 */
function getVerifiedFile(id) {
    return store.get(id) || null;
}

module.exports = { verifyDays, getVerifiedFile };
