"use strict";

/**
 * Google Drive service for Jai Durga Wine Shop.
 *
 * Single-user model: tokens stored in data/drive-tokens.json.
 * Scope: drive.file (app can only access files it created — minimal permission).
 */

const { google }  = require("googleapis");
const fs          = require("fs");
const path        = require("path");

const TOKENS_FILE  = path.join(__dirname, "..", "data", "drive-tokens.json");
const FOLDER_NAME  = "Wine Stock Sheets";
const MIME_XLSX    = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
const MIME_FOLDER  = "application/vnd.google-apps.folder";
const SCOPES       = ["https://www.googleapis.com/auth/drive.file"];

// ─── OAuth2 client factory ────────────────────────────────────────────────────

function makeClient() {
    return new google.auth.OAuth2(
        process.env.GOOGLE_CLIENT_ID,
        process.env.GOOGLE_CLIENT_SECRET,
        process.env.GOOGLE_REDIRECT_URI || "http://localhost:3000/api/drive/callback"
    );
}

// ─── Token storage helpers ────────────────────────────────────────────────────

function loadTokens() {
    try {
        if (!fs.existsSync(TOKENS_FILE)) return null;
        const raw = fs.readFileSync(TOKENS_FILE, "utf8");
        return JSON.parse(raw);
    } catch (_) {
        return null;
    }
}

function saveTokens(data) {
    const dir = path.dirname(TOKENS_FILE);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(TOKENS_FILE, JSON.stringify(data, null, 2), "utf8");
}

function deleteTokens() {
    try { if (fs.existsSync(TOKENS_FILE)) fs.unlinkSync(TOKENS_FILE); } catch (_) {}
}

// ─── Public API ───────────────────────────────────────────────────────────────

/**
 * Generate the Google OAuth consent URL.
 */
function getAuthUrl() {
    const client = makeClient();
    return client.generateAuthUrl({
        access_type: "offline",
        prompt:      "consent",
        scope:       SCOPES,
    });
}

/**
 * Exchange auth code for tokens, then save.
 * Also creates the Drive folder immediately.
 * @param {string} code
 */
async function handleCallback(code) {
    const client = makeClient();
    const { tokens } = await client.getToken(code);
    client.setCredentials(tokens);

    // Create or find folder right away
    const folderId = await findOrCreateFolder(client);

    saveTokens({ ...tokens, folderId });
    return { folderId };
}

/**
 * Returns true if drive-tokens.json exists and has tokens.
 */
function isConnected() {
    const t = loadTokens();
    return !!(t && (t.access_token || t.refresh_token));
}

/**
 * Returns a connected OAuth2 client with stored credentials.
 * Auto-refreshes access token if needed.
 */
function getAuthenticatedClient() {
    const tokens = loadTokens();
    if (!tokens) throw new Error("Google Drive not connected.");
    const client = makeClient();
    client.setCredentials(tokens);
    // Persist refreshed tokens automatically
    client.on("tokens", (refreshed) => {
        const current = loadTokens() || {};
        saveTokens({ ...current, ...refreshed });
    });
    return client;
}

/**
 * Find the "Wine Stock Sheets" folder or create it.
 * Returns folder ID.
 * @param {google.auth.OAuth2} client
 */
async function findOrCreateFolder(client) {
    const drive = google.drive({ version: "v3", auth: client });

    // Search for existing folder owned by this app
    const res = await drive.files.list({
        q: `mimeType='${MIME_FOLDER}' and name='${FOLDER_NAME}' and trashed=false`,
        fields: "files(id, name)",
        spaces: "drive",
    });

    if (res.data.files.length > 0) {
        return res.data.files[0].id;
    }

    // Create it
    const folder = await drive.files.create({
        requestBody: {
            name:     FOLDER_NAME,
            mimeType: MIME_FOLDER,
            description: "Auto-generated by Jai Durga Wine Shop Daily Stock Manager",
        },
        fields: "id",
    });
    return folder.data.id;
}

/**
 * Upload an xlsx buffer to the Drive folder.
 * @param {string} filename   e.g. "JaiDurga_Stock_2026-03-09.xlsx"
 * @param {Buffer} buffer
 * @returns {{ id: string, name: string, folderName: string }}
 */
async function uploadFile(filename, buffer) {
    const tokens = loadTokens();
    if (!tokens) throw new Error("Google Drive not connected.");

    const client = getAuthenticatedClient();
    const drive  = google.drive({ version: "v3", auth: client });

    // Ensure folder still exists (handles revoked then reconnected case)
    let folderId = tokens.folderId;
    if (!folderId) {
        folderId = await findOrCreateFolder(client);
        saveTokens({ ...tokens, folderId });
    }

    const { Readable } = require("stream");
    const stream = Readable.from(buffer);

    const res = await drive.files.create({
        requestBody: {
            name:    filename,
            parents: [folderId],
        },
        media: {
            mimeType: MIME_XLSX,
            body:     stream,
        },
        fields: "id, name",
    });

    return { id: res.data.id, name: res.data.name, folderName: FOLDER_NAME };
}

/**
 * Disconnect: delete saved tokens.
 */
function disconnect() {
    deleteTokens();
}

/**
 * Status info for the frontend.
 */
function getStatus() {
    const connected = isConnected();
    const tokens    = connected ? loadTokens() : null;
    return {
        connected,
        folderName: connected ? FOLDER_NAME : null,
        folderId:   tokens?.folderId || null,
    };
}

module.exports = { getAuthUrl, handleCallback, isConnected, uploadFile, disconnect, getStatus };
